version: "3"

services:
  order-service:
    build: ./services/order_service
    ports:
      - "8000:8000"
    depends_on:
      - payment-service
      - redis

  payment-service:
    build: ./services/payment_service
    ports:
      - "8001:8001"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"